version: '3.8'

services:
  backend:
    build:
      context: ./server
    ports:
      - "8083:8083"
    environment:
      - NODE_ENV=production
    networks:
      - pgnet

networks:
  pgnet:
    external: true


